### ISSUE TITLE
Error edit switch

### ISSUE THREAD

**Issue by miguellr** [alexemanuelol/rustPlusPlus#126]
when I try to edit a switch I am getting this error:

2023-2-06 10:07:24 Unhandled Rejection: ,Error: Invalid string length: undefined
ExpectedConstraintError > s.string.lengthLessThanOrEqual
  Invalid string length

  Expected: expected.length <= 45

  Received:
  | 'El comando personalizado para el Interruptor Inteligente:'

    at Object.run (..\rustPlusPlus-master\node_modules\@sapphire\shapeshift\src\constraints\StringConstraints.ts:40:18)
    at ..\rustPlusPlus-master\node_modules\@sapphire\shapeshift\src\validators\BaseValidator.ts:80:64
    at Array.reduce (<anonymous>)
    at StringValidator.parse (..\rustPlusPlus-master\node_modules\@sapphire\shapeshift\src\validators\BaseValidator.ts:80:27)

**Comment by miguellr** [comment]
Bug on spanish language
