### ISSUE TITLE
error undefined.json language

### ISSUE THREAD

**Issue by Owned67** [alexemanuelol/rustplusplus#153]
npm start run

> rustplusplus@1.8.0 start
> ts-node . run

Error: ENOENT: no such file or directory, open 'F:\rustplusplus\src\languages\undefined.json'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at DiscordBot.loadBotIntl (F:\rustplusplus\src\structures\DiscordBot.js:109:40)
    at new DiscordBot (F:\rustplusplus\src\structures\DiscordBot.js:64:14)
    at Object.<anonymous> (F:\rustplusplus\index.ts:29:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (F:\rustplusplus\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (F:\rustplusplus\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'F:\\rustplusplus\\src\\languages\\undefined.json'
}

fresh install, fresh discord bot.

npm@9.6.2
node 18.0.0.

**Comment by Owned67** [comment]
Solved, cannot found the information but we need to edit index.js from config folder now...

all good now
