### ISSUE TITLE
discord commands and buttons do not work (interaction failed error) for docker 

### ISSUE THREAD

**Issue by majokko** [alexemanuelol/rustplusplus#154]
whenever trying to turn off switches or using a command i am getting 
`channel.isTextbased is not a function` error

```
/app/node_modules/discord.js/src/client/actions/InteractionCreate.js:46
        if (channel && !channel.isTextBased()) return;
                                ^
TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (/app/node_modules/discord.js/src/client/actions/InteractionCreate.js:46:33)
    at Object.module.exports [as INTERACTION_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:481:22)
    at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:321:10)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
```
i updated using update.sh
and just cloned the repo again and edited credentials / instances / docker compose file and still same issue.

this seems to be a docker only issue as using `npm start run` works fine

**Comment by FaiThiX** [comment]
i had the same error when i forgot to use "npm install" and i dont know if the update file inside the docker container does this

**Comment by simpyhub** [comment]
either alle must update discord.js to be compatible with latest node or Dockerfile must be set to use a specific version as its pulling the :latest right now

**Comment by simpyhub** [comment]
i belive this is fixed with the recent code pushes alle has made, just need a need new imagine build to be released :)

**Comment by alexemanuelol** [comment]
Should be solved by running npm install, there was a bug in discord.js.
