### ISSUE TITLE
bot crash

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustPlusPlus#16]
/root/rustPlusPlus/node_modules/discord.js/src/rest/RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Invalid Form Body
embeds[0].fields[0].value: Must be 1024 or fewer in length.
    at RequestHandler.execute (/root/rustPlusPlus/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/root/rustPlusPlus/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/root/rustPlusPlus/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:175:15)
    at async sendInformationEmbed (/root/rustPlusPlus/src/inGameEvents/information.js:316:9) {
  method: 'post',
  path: '/channels/946242935995908127/messages',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [

**Comment by C74K** [comment]
and go to line 254 you should see 
 names += `[${member.name}](${STEAM_LINK}${member.steamId})`;
if you remove that and just put 

names += member.name;
