### ISSUE TITLE
bot dont start

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustplusplus#197]
/root/A/src/structures/RustPlus.js:24
const Translate = require('translate');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/A/node_modules/translate/index.min.js from /root/A/src/structures/RustPlus.js not supported.
Instead change the require of index.min.js in /root/A/src/structures/RustPlus.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/root/A/src/structures/RustPlus.js:24:19)
    at Object.<anonymous> (/root/A/src/structures/DiscordBot.js:34:18)
    at Object.<anonymous> (/root/A/index.ts:25:20) {
  code: 'ERR_REQUIRE_ESM'
}
root@czakgames:~/A#

**Comment by alexemanuelol** [comment]
Could you be more elaborate?

**Comment by C74K** [comment]
only this bot return affter use 
node .

**Comment by PandeoF1** [comment]
Run it with npm start

**Comment by C74K** [comment]
i try full re install without overwrite old files

**Comment by C74K** [comment]
fixed by full re install
