### ISSUE TITLE
How to run on a raspberry PI

### ISSUE THREAD

**Issue by CpuSocket** [alexemanuelol/rustplusplus#205]
Hello, i used this on a windows pc but when i Re-installed it on a raspberry pi it didnt work the error being:

pi@raspberrypi:~/Desktop/RustBot/rustplusplus-voice $ npm start

> rustplusplus@1.12.0 start /home/pi/Desktop/RustBot/rustplusplus-voice
> ts-node .

/home/pi/Desktop/RustBot/rustplusplus-voice/node_modules/discord.js/src/client/BaseClient.js:29
        userAgentAppendix: options.rest?.userAgentAppendix
                                        ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pi/Desktop/RustBot/rustplusplus-voice/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/pi/Desktop/RustBot/rustplusplus-voice/node_modules/discord.js/src/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rustplusplus@1.12.0 start: `ts-node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rustplusplus@1.12.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-07-16T22_51_50_349Z-debug.log

Any ideas / suggestions also very very big fan of what you do honestly its amazing very impressed cant wait to see what you can do.

- Tyler, Rasp 4

**Comment by CpuSocket** [comment]
( also this didnt work on none voice version same error )

**Comment by CpuSocket** [comment]
or create a rasp arm version of the docker please.

**Comment by kaisenn1** [comment]
are you using the latest version of nodejs?

**Comment by PandeoF1** [comment]
https://github.com/alexemanuelol/rustplusplus/pull/219

**Comment by alexemanuelol** [comment]
Using correct nodejs version should resolve it.
