### ISSUE TITLE
Problems connecting the bot to discord and starting the program

### ISSUE THREAD

**Issue by DannielStevan** [alexemanuelol/rustplusplus#208]
hi, i have many problems on start the server, I get the following error:

`danniel@:/mnt/c/Users/********/OneDrive/Escritorio/rustplusplus$ npm run start

> rustplusplus@1.12.0 start /mnt/c/Users/Danni_mxb1w8z/OneDrive/Escritorio/rustplusplus
> ts-node .

/mnt/c/Users/********/OneDrive/Escritorio/rustplusplus/node_modules/@discordjs/util/dist/index.js:35
  return () => defaultValue ??= cb();
                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.require.extensions.<computed> [as .js] (/mnt/c/Users/*********/OneDrive/Escritorio/rustplusplus/node_modules/ts-node/src/index.ts:1608:43)    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/mnt/c/Users/*********/OneDrive/Escritorio/rustplusplus/node_modules/@discordjs/rest/src/lib/RequestManager.ts:6:22)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rustplusplus@1.12.0 start: `ts-node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rustplusplus@1.12.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/danniel/.npm/_logs/2023-07-22T18_28_54_381Z-debug.log
danniel@*****:/mnt/c/Users/******/OneDrive/Escritorio/rustplusplus$`

**Comment by DannielStevan** [comment]
Thank you very much in advance, I hope you can help me

**Comment by C74K** [comment]
[npm install](https://github.com/alexemanuelol/rustplusplus/blob/master/docs/documentation.md)

**Comment by DannielStevan** [comment]
> [npm install](https://github.com/alexemanuelol/rustplusplus/blob/master/docs/documentation.md)

`> rustplusplus@1.12.0 start /mnt/c/Users/Danni_mxb1w8z/OneDrive/Escritorio/rustplusplus
> ts-node . "run"

/mnt/c/Users/Danni_mxb1w8z/OneDrive/Escritorio/rustplusplus/node_modules/@discordjs/util/dist/index.js:35
  return () => defaultValue ??= cb();
                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.require.extensions.<computed> [as .js] (/mnt/c/Users/Danni_mxb1w8z/OneDrive/Escritorio/rustplusplus/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/mnt/c/Users/Danni_mxb1w8z/OneDrive/Escritorio/rustplusplus/node_modules/@discordjs/rest/src/lib/RequestManager.ts:6:22)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rustplusplus@1.12.0 start: `ts-node . "run"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rustplusplus@1.12.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/danniel/.npm/_logs/2023-07-23T05_39_17_216Z-debug.log`

despite running npm install it still doesn't work :(

**Comment by DannielStevan** [comment]
I was able to solve the error, the problem is basically the console I was using at the time, I was using the cmd that comes with Windows by default and this wouldn't let me start it, when installing git and using git bash I was able to start the bot, maybe this information will be useful to people who have this same error. Thank you very much and I hope you are well

**Comment by alexemanuelol** [comment]
Hi, could it be that you're running a different version of nodejs?
