### ISSUE TITLE
Disconnects from server after a command is issued within Discord

### ISSUE THREAD

**Issue by Profited** [alexemanuelol/rustplusplus#245]
```2023-9-23 13:26:59 1124195619658010794 Rustoria.co - US Medium CONNECTING: CONNECTING TO SERVER...
2023-9-23 13:28:05 1124195619658010794 Rustoria.co - US Medium CONNECTED: CONNECTED TO SERVER.
2023-9-23 13:28:06 1124195619658010794 Rustoria.co - US Medium CONNECTED: RUSTPLUS OPERATIONAL.
(node:19698) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
2023-9-23 13:28:13 1124195619658010794 Rustoria.co - US Medium EVENT: Cargo Ship enters the map from North West.
2023-9-23 13:28:55 1124195619658010794 Rustoria.co - US Medium INFO: Message: hi, User: XX (XX)
2023-9-23 13:28:58 1124195619658010794 Rustoria.co - US Medium ERROR: Timeout reached while waiting for response.
2023-9-23 13:28:58 1124195619658010794 Rustoria.co - US Medium Error
2023-9-23 13:28:58 1124195619658010794 Rustoria.co - US Medium     at Logger.log (/root/rustplusplus/src/structures/Logger.js:99:39)
2023-9-23 13:28:58 1124195619658010794 Rustoria.co - US Medium     at RustPlus.log (/root/rustplusplus/src/structures/RustPlus.js:268:21)
2023-9-23 13:28:58 1124195619658010794 Rustoria.co - US Medium     at RustPlus.isResponseValid (/root/rustplusplus/src/structures/RustPlus.js:681:18)
2023-9-23 13:28:58 1124195619658010794  #Rustoria.co - US Medium     at Timeout.pollingHandler [as _onTimeout] (/root/rustplusplus/src/handlers/pollingHandler.js:37:30)
2023-9-23 13:29:00 INFO: Discord Message - Guild: XX's server (XX), Channel: teamchat (XX), User: XX (XX), Message: test.
2023-9-23 13:29:09 INFO: Discord Message - Guild: XX's server (XX), Channel: teamchat (XX), User: XX (XX), Message: does it work?.
2023-9-23 13:29:13 INFO: Discord Message - Guild: XX's server (XX), Channel: teamchat (XX), User: XX (XX), Message: no.
2023-9-23 13:29:15 1124195619658010794 Rustoria.co - US Medium DISCONNECTED: DISCONNECTED FROM SERVER.
2023-9-23 13:29:15 1124195619658010794 Rustoria.co - US Medium RECONNECTING: RECONNECTING TO SERVER...
2023-9-23 13:29:35 1124195619658010794 Rustoria.co - US Medium CONNECTING: CONNECTING TO SERVER...
2023-9-23 13:30:07 1124195619658010794 Rustoria.co - US Medium CONNECTED: CONNECTED TO SERVER.
2023-9-23 13:30:08 1124195619658010794 Rustoria.co - US Medium CONNECTED: RUSTPLUS OPERATIONAL.
2023-9-23 13:30:15 1124195619658010794 Rustoria.co - US Medium EVENT: Cargo Ship enters the map from North West.
2023-9-23 13:30:25 INFO: Discord Message - Guild: XX's server (XX), Channel: teamchat (XX), User: XX (XX), Message: rust is dumb.
2023-9-23 13:30:34 1124195619658010794 Rustoria.co - US Medium DISCONNECTED: DISCONNECTED FROM SERVER.
2023-9-23 13:30:35 1124195619658010794 Rustoria.co - US Medium RECONNECTING: RECONNECTING TO SERVER...
2023-9-23 13:30:55 1124195619658010794 Rustoria.co - US Medium CONNECTING: CONNECTING TO SERVER...```

> Tried this on three different hosting providers and also on my own network. Not sure why it disconnects after a command is sent, why god why.

**Comment by alexemanuelol** [comment]
Rustoria goes above and beyond to get rid of rust+ bots so Im not surprised you're having problems on those servers

**Comment by Profited** [comment]
> Rustoria goes above and beyond to get rid of rust+ bots so Im not surprised you're having problems on those servers

Ouch. That sucks. They suck!!
