### ISSUE TITLE
ERROR: Message send failed: ,DiscordAPIError[50035]: Invalid Form Body embeds[0].thumbnail.url[URL_TYPE_INVALID_URL]: Not a well formed URL.

### ISSUE THREAD

**Issue by DoogeJ** [alexemanuelol/rustplusplus#255]
When trying to pair a server (Rustafied.com - EU Trio II) I get this today: 

```2023-10-17 21:07:24 ERROR: Message send failed: ,DiscordAPIError[50035]: Invalid Form Body
embeds[0].thumbnail.url[URL_TYPE_INVALID_URL]: Not a well formed URL.
2023-10-17 21:07:24 ERROR: Unhandled Rejection: ,TypeError: Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
    at Object.sendServerMessage (C:\dev\rustplusplus\src\discordTools\discordMessages.js:71:63)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pairingServer (C:\dev\rustplusplus\src\util\FcmListener.js:248:5)
```

I did run `update.bat` but no success.

**Comment by alexemanuelol** [comment]
Solved in: afbdc686c1422d4e359cbc58de57c16302b9d021
