### ISSUE TITLE
Unhandled Rejection: ,TypeError: Cannot read properties of undefined (reading 'length') on player command

### ISSUE THREAD

**Issue by nephacks** [alexemanuelol/rustplusplus#273]
running the in-game player command causes an unhandled rejection in the console

```
2023-11-26 02:17:00 ERROR: Unhandled Rejection: ,TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at RustPlus.getCommandPlayer (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\src\structures\RustPlus.js:1901:91)
    at Object.inGameCommandHandler (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\src\handlers\inGameCommandHandler.js:130:49)
    at messageBroadcastTeamMessage (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\src\rustplusEvents\message.js:107:44)
    at messageBroadcast (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\src\rustplusEvents\message.js:54:9)
    at Object.execute (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\src\rustplusEvents\message.js:40:13)
    at RustPlus.<anonymous> (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\src\structures\RustPlus.js:119:52)
    at RustPlus.emit (node:events:514:28)
    at RustPlus.emit (node:domain:489:12)
    at WebSocket.<anonymous> (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\node_modules\@liamcottle\rustplus.js\rustplus.js:100:22)
    at WebSocket.emit (node:events:514:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\node_modules\ws\lib\websocket.js:1192:20)
    at Receiver.emit (node:events:514:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\node_modules\ws\lib\receiver.js:545:14)
    at Receiver.getData (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\node_modules\ws\lib\receiver.js:478:17)
    at Receiver.startLoop (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\node_modules\ws\lib\receiver.js:167:22)
    at Receiver._write (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\node_modules\ws\lib\receiver.js:93:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Receiver.Writable.write (node:internal/streams/writable:337:10)
    at Socket.socketOnData (C:\Users\nephacks\Documents\rustplusplus\rustplusplus\node_modules\ws\lib\websocket.js:1286:35)
```

**Comment by alexemanuelol** [comment]
Fixed in: 6ac02e29620b215a287328cf85cf714fa5b421c5
