### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by diifark** [alexemanuelol/rustplusplus#299]
root@166508:~/rustplusplus# npm run start

> rustplusplus@1.15.0 start /root/rustplusplus
> ts-node .

/root/rustplusplus/node_modules/discord.js/src/client/BaseClient.js:45
        userAgentAppendix: options.rest?.userAgentAppendix
                                        ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .js] (/root/rustplusplus/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/rustplusplus/node_modules/discord.js/src/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rustplusplus@1.15.0 start: `ts-node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rustplusplus@1.15.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-03-08T05_46_26_492Z-debug.log

**Comment by waaynee** [comment]
Did you fix that error? If yes, could you share how to?
