### ISSUE TITLE
ERROR: SyntaxError: Unexpected token in JSON at posititon 0

### ISSUE THREAD

**Issue by alexemanuelol** [alexemanuelol/rustplusplus#309]
Known error that can occur whenever PC/Server crashes. No solution to it yet but there is a branch that can be run to help finding the cause of the problem.

To switch to the instance_invalid branch, do the following in the console:

```
git stash
git fetch --all
git checkout instance_invalid
git stash pop
```

By running this branch it will print out more information everytime we write to the instance file.

If you are running the branch and the error occur, please paste your log here.

![error](https://github.com/alexemanuelol/rustplusplus/assets/18254752/54a741f7-fee4-4685-9efd-a3af44e6d08f)

**Comment by alexemanuelol** [comment]
Currently working on switching to typescript. By doing this I will be able to check the type before writing the instance file. So hopefully that will solve this issue when I get there.

**Comment by sebastienvercammen** [comment]
Still happening as of today. Had it happen as the service had crashed overnight.

```powershell
PS D:\repos\rustplusplus> npm start run

> rustplusplus@1.22.0 start
> ts-node . run

2026-2-18 16:08:50 ERROR: SyntaxError: Unexpected token '', ""... is not valid JSON
```

The `instance_invalid` logs don't show any additional details (`discordBot.log` received new input, the log file with ID as filename did not):

```
{"level":"error","message":"2026-2-18 16:08:50 | ERROR: SyntaxError: Unexpected token '\u0000', \"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\"... is not valid JSON"}
```

With `showCallStackError` enabled:

```powershell
2026-2-18 16:25:37 ERROR: SyntaxError: Unexpected token '', ""... is not valid JSON
2026-2-18 16:25:37 Error
2026-2-18 16:25:37     at Logger.log (D:\repos\rustplusplus\src\structures\Logger.js:81:40)
2026-2-18 16:25:37     at DiscordBot.log (D:\repos\rustplusplus\src\structures\DiscordBot.js:192:21)
2026-2-18 16:25:37     at Object.execute (D:\repos\rustplusplus\src\discordEvents\error.js:24:16)
2026-2-18 16:25:37     at DiscordBot.<anonymous> (D:\repos\rustplusplus\src\structures\DiscordBot.js:103:56)
2026-2-18 16:25:37     at DiscordBot.emit (node:events:508:28)
2026-2-18 16:25:37     at DiscordBot.emit (node:domain:489:12)
2026-2-18 16:25:37     at emitUnhandledRejectionOrErr (node:events:391:10)
2026-2-18 16:25:37     at processTicksAndRejections (node:internal/process/task_queues:91:21)
```

(Which is a bit of a waste, you should probably not be stringifying errors or recreating stacks in your logger with `new Error()`, which just ends up showing the logger stack instead of the error stack.)

When I replaced your logged stack with the actual failing stack:

```powershell
SyntaxError: Unexpected token '', ""... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.readInstanceFile (D:\repos\rustplusplus\src\util\instanceUtils.js:47:21)
    at module.exports (D:\repos\rustplusplus\src\util\CreateInstanceFile.js:74:34)
    at Object.execute (D:\repos\rustplusplus\src\discordEvents\ready.js:32:50)
    at DiscordBot.<anonymous> (D:\repos\rustplusplus\src\structures\DiscordBot.js:100:58)
    at Object.onceWrapper (node:events:623:26)
    at DiscordBot.emit (node:events:508:28)
    at DiscordBot.emit (node:domain:489:12)
    at WebSocketManager.triggerClientReady (D:\repos\rustplusplus\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:17)
    at WebSocketManager.checkShardsReady (D:\repos\rustplusplus\node_modules\discord.js\src\client\websocket\WebSocketManager.js:367:10)
```

Which is correct: The `instances/{guild_id}.json` file was corrupted (19KB of null bytes). Renaming/deleting the file gets the bot to start again (but recreates all channels since it no longer knows the old IDs).

**Comment by YakovAU** [comment]
this might be caused by Fs.writeFileSync() being used directly, which can produce corrupted (all-null-byte) files if the process crashes or is interrupted mid-write. Im trying a fix, along with some more error handling, since the bot crashes in certain circumstances unrelated to this issue and the bot goes offline.
