### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by Ve0ny** [alexemanuelol/rustplusplus#341]
G:\temp\1>npm start run

> rustplusplus@1.16.0 start
> ts-node . run

G:\temp\1\node_modules\ts-node\dist\index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module G:\temp\1\node_modules\translate\index.min.js from G:\temp\1\src\structures\RustPlus.js not supported.
Instead change the require of index.min.js in G:\temp\1\src\structures\RustPlus.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (G:\temp\1\node_modules\ts-node\dist\index.js:851:20)
    at Object.<anonymous> (G:\temp\1\src\structures\RustPlus.js:24:19)
    at m._compile (G:\temp\1\node_modules\ts-node\dist\index.js:857:29) {
  code: 'ERR_REQUIRE_ESM'
}

G:\temp\1>

**Comment by Ve0ny** [comment]
This error began to occur after installing “punycode”, I assumed that because of this the bot did not see the bot that I launched, because something was written about it in the console.
