### ISSUE TITLE
Server connect: TypeError: Cannot read properties of undefined (reading 'steamId')

### ISSUE THREAD

**Issue by njaksch** [alexemanuelol/rustplusplus#358]
When clicking on "Connect" button in discord, the server won't be connected and the console prints the following error:

```
0|rustplusplus  | 2024-8-18 16:34:21 ERROR: Unhandled Rejection: ,TypeError: Cannot read properties of undefined (reading 'steamId')
0|rustplusplus  | TypeError: Cannot read properties of undefined (reading 'steamId')
0|rustplusplus  |     at Object.getServerEmbed (/home/*****/rustplusplus/src/discordTools/discordEmbeds.js:72:47)
0|rustplusplus  |     at Object.sendServerMessage (/home/*****/rustplusplus/src/discordTools/discordMessages.js:63:42)
0|rustplusplus  |     at module.exports (/home/*****/rustplusplus/src/handlers/buttonHandler.js:440:35)
0|rustplusplus  |     at Object.execute (/home/*****/rustplusplus/src/discordEvents/interactionCreate.js:45:49)
0|rustplusplus  |     at DiscordBot.<anonymous> (/home/*****/rustplusplus/src/structures/DiscordBot.js:103:56)
0|rustplusplus  |     at DiscordBot.emit (node:events:519:28)
0|rustplusplus  |     at DiscordBot.emit (node:domain:488:12)
0|rustplusplus  |     at InteractionCreateAction.handle (/home/*****/rustplusplus/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
0|rustplusplus  |     at Object.module.exports [as INTERACTION_CREATE] (/home/*****/rustplusplus/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
0|rustplusplus  |     at WebSocketManager.handlePacket (/home/*****/rustplusplus/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
0|rustplusplus  |     at WebSocketShard.onPacket (/home/*****/rustplusplus/node_modules/discord.js/src/client/websocket/WebSocketShard.js:494:22)
0|rustplusplus  |     at WebSocketShard.onMessage (/home/*****/rustplusplus/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
0|rustplusplus  |     at callListener (/home/*****/rustplusplus/node_modules/ws/lib/event-target.js:290:14)
0|rustplusplus  |     at WebSocket.onMessage (/home/*****/rustplusplus/node_modules/ws/lib/event-target.js:209:9)
0|rustplusplus  |     at WebSocket.emit (node:events:519:28)
0|rustplusplus  |     at WebSocket.emit (node:domain:488:12)
0|rustplusplus  |     at Receiver.receiverOnMessage (/home/*****/rustplusplus/node_modules/ws/lib/websocket.js:1203:20)
0|rustplusplus  |     at Receiver.emit (node:events:519:28)
0|rustplusplus  |     at Receiver.emit (node:domain:488:12)
0|rustplusplus  |     at Receiver.dataMessage (/home/*****/rustplusplus/node_modules/ws/lib/receiver.js:565:14)
0|rustplusplus  |     at Receiver.getData (/home/*****/rustplusplus/node_modules/ws/lib/receiver.js:483:17)
0|rustplusplus  |     at Receiver.startLoop (/home/*****/rustplusplus/node_modules/ws/lib/receiver.js:172:22)
```

**Comment by njaksch** [comment]
Docker version works fine. Should be a problem on my end, sorry.
