### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by EricPlays61** [alexemanuelol/rustplusplus#372]
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\rust\node_modules\translate\index.min.js from C:\rust\src\structures\RustPlus.js not supported.
Instead change the require of index.min.js in C:\rust\src\structures\RustPlus.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (C:\rust\node_modules\ts-node\dist\index.js:851:20)
    at Object.<anonymous> (C:\rust\src\structures\RustPlus.js:24:19)
    at m._compile (C:\rust\node_modules\ts-node\dist\index.js:857:29)
    at require.extensions.<computed> [as .js] (C:\rust\node_modules\ts-node\dist\index.js:859:16)
    at Object.<anonymous> (C:\rust\src\structures\DiscordBot.js:35:18)
    at m._compile (C:\rust\node_modules\ts-node\dist\index.js:857:29)
    at require.extensions.<computed> [as .js] (C:\rust\node_modules\ts-node\dist\index.js:859:16)
    at Object.<anonymous> (C:\rust\index.ts:24:20)
    at m._compile (C:\rust\node_modules\ts-node\dist\index.js:857:29)
    at require.extensions.<computed> [as .ts] (C:\rust\node_modules\ts-node\dist\index.js:859:16)
    at phase4 (C:\rust\node_modules\ts-node\dist\bin.js:466:20)
    at bootstrap (C:\rust\node_modules\ts-node\dist\bin.js:54:12)
    at main (C:\rust\node_modules\ts-node\dist\bin.js:33:12)
    at Object.<anonymous> (C:\rust\node_modules\ts-node\dist\bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}

I don't know what to do or what i did it worked one day and stopped the next.

**Comment by alexemanuelol** [comment]
You can try to remove your node_modules directory and run `npm install` again.
