### ISSUE TITLE
ERROR: Unhandled Rejection: ,Error: interior hyphen

### ISSUE THREAD

**Issue by HeresJohnny320** [alexemanuelol/rustplusplus#374]
2024-9-27 09:01:38 ERROR: Unhandled Rejection: ,Error: interior hyphen
Error: interior hyphen
    at Function.fromString (/root/rustplusbot/node_modules/@liamcottle/push-receiver/node_modules/long/dist/long.js:261:19)
    at getCheckinRequest (/root/rustplusbot/node_modules/@liamcottle/push-receiver/src/gcm/index.js:121:14)
    at checkIn (/root/rustplusbot/node_modules/@liamcottle/push-receiver/src/gcm/index.js:35:18)
    at async Client.connect (/root/rustplusbot/node_modules/@liamcottle/push-receiver/src/client.js:45:5)

**Comment by EricPlays61** [comment]
I am also having this problem

**Comment by alexemanuelol** [comment]
This might have something to do with credentials. Try to remove your credentials and then add new ones. Then perhaps pairing should work again.
