### ISSUE TITLE
Error when running on Ubuntu 22.04

### ISSUE THREAD

**Issue by DenyaBanan** [alexemanuelol/rustplusplus#378]
When running npm start run, I get an error in the console

> rustplusplus@1.20.0 start
> ts-node . "run"

/rustplusplus/node_modules/discord.js/src/client/BaseClient.js:21
    if (options.rest?.userAgentAppendix) {
                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/rustplusplus/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/rustplusplus/node_modules/discord.js/src/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by FaiThiX** [comment]
try to remove your node_modules folder and also the package-lock.json and rerun "npm install"
