### ISSUE TITLE
Custom map = Not Working bot - Craash

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustPlusPlus#41]
Bot dont work on custom maps

"/root/rustPlusPlus/src/util/map.js:49
                    rustplus.map.monumentInfo[monument.token].radius) {
                                                              ^

TypeError: Cannot read properties of undefined (reading 'radius')
    at Object.getPos (/root/rustPlusPlus/src/util/map.js:49:63)
    at Player.updatePos (/root/rustPlusPlus/src/structures/Player.js:85:28)
    at new Player (/root/rustPlusPlus/src/structures/Player.js:21:14)
    at Team.addPlayer (/root/rustPlusPlus/src/structures/Team.js:86:31)
    at Team.updateTeam (/root/rustPlusPlus/src/structures/Team.js:58:22)
    at new Team (/root/rustPlusPlus/src/structures/Team.js:14:14)
    at Object.pollingHandler (/root/rustPlusPlus/src/handlers/pollingHandler.js:28:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.3.1
"

**Comment by goldbeg** [comment]
Hey @C74K, Reinstall the Bot it seemed to work for me. Clear all the Packages installed and reinstalled.

**Comment by C74K** [comment]
bot working i removed .radius from code and map works
