### ISSUE TITLE
Bot crashing

### ISSUE THREAD

**Issue by YayoAstur** [alexemanuelol/rustPlusPlus#68]
Hi! My bot crashed this morning with the next error (while we were getting raided 🙃): 

`2022-9-04 02:39:18 143428962834448386 CENSOREDSERVERNAME ERROR: Response contain error property with value: not_found.
/home/rust/rustPlusPlus/src/discordTools/discordEmbeds.js:236
            title: `${instance.serverList[serverId][type][entityId].name}`,
                                                   ^
TypeError: Cannot read properties of undefined (reading 'undefined')
    at Object.getNotFoundSmartDeviceEmbed (/home/rust/rustPlusPlus/src/discordTools/discordEmbeds.js:236:52)
    at Object.sendSmartSwitchMessage (/home/rust/rustPlusPlus/src/discordTools/discordMessages.js:74:31)
    at Object.handler (/home/rust/rustPlusPlus/src/handlers/smartSwitchHandler.js:22:47)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

Starting the bot again ends in crashing instantly with a very similar error but with an extra line at the end:

`2022-9-04 07:19:46 143428962834448386 CENSOREDSERVERNAME CONNECTED: SUCCESSFULLY CONNECTED!
2022-9-04 07:19:47 143428962834448386 CENSOREDSERVERNAME ERROR: Response contain error property with value: not_found.
/home/rust/rustPlusPlus/src/discordTools/discordEmbeds.js:236
            title: `${instance.serverList[serverId][type][entityId].name}`,
                                                   ^
TypeError: Cannot read properties of undefined (reading 'undefined')
    at Object.getNotFoundSmartDeviceEmbed (/home/rust/rustPlusPlus/src/discordTools/discordEmbeds.js:236:52)
    at Object.sendSmartSwitchMessage (/home/rust/rustPlusPlus/src/discordTools/discordMessages.js:74:31)
    at module.exports (/home/rust/rustPlusPlus/src/discordTools/SetupSwitches.js:32:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.execute (/home/rust/rustPlusPlus/src/rustplusEvents/connected.js:129:9)
`

Running on Ubuntu server 20.04 with NodeJS v16.17.0

**Comment by alexemanuelol** [comment]
This might be because of the move of smart devices to serverList rather than directly in the instance file. This can be solved by removing your instance file `src/instances/928946892759285.json`.
