### ISSUE TITLE
Running through cPanel throws: reading 'timeoutType': undefined

### ISSUE THREAD

**Issue by GhostyIs1337** [alexemanuelol/rustPlusPlus#90]
```
returncode: 0
stdout:
> rustPlusPlus@1.2.0 start
> ts-node . "run"

2022-10-13 09:49:30 ERROR: {}
2022-10-13 09:49:30 Unhandled Rejection: ,TypeError: Cannot read properties of undefined (reading 'timeoutType'): undefined
TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/home/ghostyso/nodevenv/repositories/rustPlusPlus/16/lib/node_modules/undici/lib/client.js:1167:29)
    at resume (/home/ghostyso/nodevenv/repositories/rustPlusPlus/16/lib/node_modules/undici/lib/client.js:1131:3)
    at connect (/home/ghostyso/nodevenv/repositories/rustPlusPlus/16/lib/node_modules/undici/lib/client.js:1116:3)
stderr:
```

![image](https://user-images.githubusercontent.com/20501149/195531178-545b1ba5-9002-4a0c-8266-aea271de4127.png)

Node version: 16.17.1

However, running the same directory directly with the terminal works fine.

This seems to match for the undici library: https://github.com/nodejs/undici/issues/1087

My currently installed version seems to be 5.11.0

  "name": "undici",
  "version": "5.11.0",

**Comment by C74K** [comment]
i dont understand ?? you make web panel for bot ?

**Comment by GhostyIs1337** [comment]
> i dont understand ?? you make web panel for bot ?

No, it's just so the bot can run continuously without the need to SSH onto the VPS and run commands, especially when you can't install pm2 globally, because you don't have root access.

**Comment by GhostyIs1337** [comment]
> > i dont understand ?? you make web panel for bot ?
> 
> No, it's just so the bot can run continuously without the need to SSH onto the VPS and run commands, especially when you can't install pm2 globally, because you don't have root access.

Well, for anyone else that wants to run it on a VPS - if you have ssh access:

`nohup npm start run`
`disown`
