### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\opt\rust\rustPlusPlus\src\languages\undefined.json'

### ISSUE THREAD

**Issue by andrewdens** [alexemanuelol/rustPlusPlus#92]
Tried updating with the update.bat script and then this started coming up. I also tried to refresh my entire folder and follow the guide to reinstall but having same issue.

PS C:\opt\rust\rustPlusPlus> npm start run
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> rustPlusPlus@1.2.0 start
> ts-node . "run"

Error: ENOENT: no such file or directory, open 'C:\opt\rust\rustPlusPlus\src\languages\undefined.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at DiscordBot.loadBotIntl (C:\opt\rust\rustPlusPlus\src\structures\DiscordBot.js:71:40)
    at new DiscordBot (C:\opt\rust\rustPlusPlus\src\structures\DiscordBot.js:38:14)
    at Object.<anonymous> (C:\opt\rust\rustPlusPlus\index.ts:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (C:\opt\rust\rustPlusPlus\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (C:\opt\rust\rustPlusPlus\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\opt\\rust\\rustPlusPlus\\src\\languages\\undefined.json'

**Comment by andrewdens** [comment]
Had to setup the config as per announcement notes on discord
